### ISSUE TITLE
Why does the class name do not match the file name?

### ISSUE THREAD

**Issue by AliaksandrFiodarau3** [nexon543/Final_Task_1#11]
https://github.com/nexon543/Final_Task_1/blob/3df19c4ed7d32e033854e39c7dd1ed21db0344c7/src/main/java/com/epam/provider/dao/UserDAO.java#L6

**Comment by nexon543** [comment]
removed this files
problems with git
45ce3b71bbb229217e5627ede5edd7343818a48e
