### ISSUE TITLE
Why do you implement these methods if you use AbstractionDao? 

### ISSUE THREAD

**Issue by AliaksandrFiodarau3** [nexon543/Final_Task_1#15]
https://github.com/nexon543/Final_Task_1/blob/dc99f4e5c2cd96e6321660570fb7019acb609b3e/src/main/java/com/epam/provider/dao/impl/UserDAOImpl.java#L46-L71

**Comment by nexon543** [comment]
it is my inaccuracy
https://github.com/nexon543/Final_Task_1/blob/master/src/main/java/com/epam/provider/dao/impl/UserDaoImpl.java
