### ISSUE TITLE
This is protection against NPE Exception?

### ISSUE THREAD

**Issue by AliaksandrFiodarau3** [nexon543/Final_Task_1#17]
https://github.com/nexon543/Final_Task_1/blob/530d679bfd119e1d1403308f58001bbd36f8cfa9/src/main/java/com/epam/provider/web/controller/command/impl/LoginCommand.java#L41

**Comment by nexon543** [comment]
no, there ServiceException is catched
a21d078c463b880eb40c6f47688fa891686e0216
