### ISSUE TITLE
I guess this should be an interface

### ISSUE THREAD

**Issue by vatolinrp** [nexon543/Final_Task_1#20]
https://github.com/nexon543/Final_Task_1/blob/a21d078c463b880eb40c6f47688fa891686e0216/src/main/java/com/epam/provider/service/Service.java#L4

**Comment by nexon543** [comment]
created interfaces
https://github.com/nexon543/Final_Task_1/blob/master/src/main/java/com/epam/provider/service/TariffService.java

**Comment by vatolinrp** [comment]
better
