### ISSUE TITLE
idProfiles - i guess you can pick a better name

### ISSUE THREAD

**Issue by vatolinrp** [nexon543/Final_Task_1#25]
https://github.com/nexon543/Final_Task_1/blob/b58a1e2c509b105009271c7beb3fec52f6a22583/src/main/java/com/epam/provider/model/Profile.java#L8

**Comment by nexon543** [comment]
106f5311018609fafe9dee5beeff5ae109cadd99

**Comment by vatolinrp** [comment]
better
