### ISSUE TITLE
Please move it outside of this class.

### ISSUE THREAD

**Issue by AliaksandrFiodarau3** [nexon543/Final_Task_1#3]
https://github.com/nexon543/Final_Task_1/blob/e7280feef1ff32d04ce3a221a16dcea1060689bc/src/main/java/com/epam/provider/dao/pool/ConnectionPool.java#L105

**Comment by nexon543** [comment]
6246e7d7c150ad56d54560b62ec435d02b24e171

**Comment by AliaksandrFiodarau3** [comment]
I like it)) In my opinion you can close the issue.
